### ISSUE TITLE
ありがと~☆ヽ(∇⌒ヽ)(ノ⌒∇)ノ☆

### ISSUE THREAD

**Issue by ff14rokurou** [grindingcoil/act_timeline#39]
配布ありがとうございます

おかげで攻略が楽になりました♪
「タイムラインの自作方法」とにらめっこして
１．塔踏みで変動する3種類のアクティビティをログ正規表現でcustom triggerで音を鳴らす
２．w5以降短縮やスキップで変動するアラガンフィールドはspell timerで音鳴らす
３．timelineで変動のないものだけalertallで音を鳴らす
という感じでtimelineをアレンジして利用させて貰ってます
音はSofTalkで「地雷」「ドレッド」「防衛反応」など作って利用してますがかなりいい感じです
これからも開発頑張ってください(｀･ω･´)ゞ

**Comment by grindingcoil** [comment]
応援どもです！なにか欲しい機能などあればお気軽にどうぞ
