### ISSUE TITLE
Soundの再生をACT側で再生してください

### ISSUE THREAD

**Issue by xtuaok** [grindingcoil/act_timeline#41]
現状だとプラグイン側でSystem.Media.SoundPlayerを使って再生していますが、ACTのAPIにFormActMain.PlaySoundDelegate Delegateというのがあり、wavファイルを渡すと再生できます。
プラグインではこちらを使うほうが筋が通っており、共通したサウンド設定や別のサウンド系プラグインを使うことが可能にあります。

**Comment by grindingcoil** [comment]
makes sense. will do.

**Comment by grindingcoil** [comment]
Environment -> "Play sound by ACT" チェックボックスを有効にするとACT側で再生されるようになります。
TTS対応のため元のコードも残してます。
